### ISSUE TITLE
Some unusual differences between master(7b0eb) and v1.0.3

### ISSUE THREAD

**Issue by Lin-Buo-Ren** [hamano/apache-mod-markdown#13]
Hi, I built and installed commit 7b0eb6854a5b4f0fe2b540ee54c0a4815c8e84e4 and 1.0.3 and notice some unusual differences:

* In 1.0.3 the built module in installed as /usr/lib/apache2/modules/**mod_markdown.so** however in commit 7b0eb6854a5b4f0fe2b540ee54c0a4815c8e84e4 it is /usr/lib/apache2/modules/**libmodmarkdown.so** instead
* in 1.0.3 the mod_markdown.so file has -rwxr-xr-x permission instead of -rw-r--r--, not sure if it's same in commit 7b0eb6854a5b4f0fe2b540ee54c0a4815c8e84e4 though

![default](https://cloud.githubusercontent.com/assets/13408130/21311531/a42d58b4-c622-11e6-8a6e-a805a9c596c9.png)

Not sure if it's really an issue or if already fixed, though.

**Comment by hamano** [comment]
Probably it was fixed at 5af1d3a.
Try it please.

**Comment by Lin-Buo-Ren** [comment]
Verified, it works.
