### ISSUE TITLE
1st level header doesn't translated as <title>

### ISSUE THREAD

**Issue by Lin-Buo-Ren** [hamano/apache-mod-markdown#14]
Page: <https://sites.ind.ntou.edu.tw/>
Source: <https://github.com/ntouind/sites.ind.ntou.edu.tw/blob/master/README.markdown>

The output page doesn't contain any <title> elements.

I noticed that in [mod_markdown.c](https://github.com/hamano/apache-mod-markdown/blob/master/mod_markdown.c) the title has been handled but somehow not worked properly

```c
    title = mkd_doc_title(doc);
    if (title) {
        ap_rprintf(r, "<title>%s</title>\n", title);
}
```

I'm currently using 1.0.3

**Comment by hamano** [comment]
you need to specify title block for title:

~~~
% title
% author(s) (separated by semicolons)
% date
~~~

see http://pandoc.org/MANUAL.html

**Comment by Lin-Buo-Ren** [comment]
Thanks!
