### ISSUE TITLE
Build instructions broken

### ISSUE THREAD

**Issue by arkanovicz** [hamano/apache-mod-markdown#25]
The doc says:
"Note: <DISCOUNT_DIR> is the directory that contains the include directory that contains mkdio.h Probably you need to specify --with-discount=/usr or --with-discount=/usr/local"
But on recent debian based distros, the path to the file mkdio.h is:
   /usr/include/x86_64-linux-gnu/mkdio.h
I symlinked it to /usr/include/mkdio.h and it seemed to work.

**Comment by hamano** [comment]
Hi,
./configure --with-discount=/usr will find /usr/include/x86_64-linux-gnu/mkdio.h
see:
https://github.com/hamano/apache-mod-markdown/blob/master/configure.ac#L29

so no need to link symlinks.
