### ISSUE TITLE
How to use MarkdownFooterHtml/MarkdownHeaderHtml

### ISSUE THREAD

**Issue by netniV** [hamano/apache-mod-markdown#27]
I'm trying to utilise these to add standard copyright info to each Markdown page but I can't seem to get the configuration options working. I've tried using a filename, an absolute filename, a character string but none of these seem to be actually adding anything to the pages.

Not worked:
```
MarkdownFooterHtml    markdown.footer
MarkdownHeaderHtml   markdown.header
```

Not worked:
```
MarkdownFooterHtml    /usr/share/markdown.footer
MarkdownHeaderHtml    /usr/share/markdown.header
```

Not worked:
```
MarkdownFooterHtml    "<hr><h1>Testing Headers</h1><hr>"
MarkdownFooterHtml    "<hr><h1>Testing Footers</h1><hr>"
```

**Comment by hamano** [comment]
I tried to implement this, but I had abort this because there really was no need.
Copyright would be better was in markdown. because mod_markdown has feature that fetch raw md file. try "?raw" url parameter.

**Comment by netniV** [comment]
Would that be github compatible?  Just curious because the plan is to try and use the same source for local and GitHub-based pages.

**Comment by hamano** [comment]
It is not displayed the same as github completely.
They use ruby's markdown renderer.
Of course we can imitate it by CSS.

**Comment by netniV** [comment]
I meant the markdown of `?raw`, guess I could test it on there.

**Comment by hamano** [comment]
Initially, I planed MarkdownHeaderHtml parameter to add text to only rendered html. ex: adsense code.
Copyright should be write in original markdown.

**Comment by hamano** [comment]
May the concept of copyright is different in our country and your country ...
Copyright is for raw content, not add  to html dynamically.
If copyright date is added during rendering, the copyright rule after death will be meaningless.
If you add copyright to only html footer, since everyone can fetch raw contents by add "?raw" parameter, it will be possible to get content without copyright notice.
The navigation menu is the usage that I assumed.

**Comment by netniV** [comment]
I will take your point on the copyright via ?raw.  I'll update my conversion scripts to put in the copyright notice.  I'll just have to manually strip it out again when I'm making the master document.  However, the layout header/footer would still be desired to get a proper layout when using it directly on a site rather than via github.

**Comment by netniV** [comment]
I was still hoping to provide a skeleton outline to the docs to make it match the rest of the site.  That is were the Header/Footer would have come in useful. Can't you make it do something as simple as expect a filename and then pass the contents through untouched?

**Comment by hamano** [comment]
I'll welcome your Pull Request.
Thanks.

**Comment by netniV** [comment]
So I've implemented quite a few changes in the code to handle this, including a config check which occurs after the server is started to verify that the files in question exist and are readable.  This now compiles but I haven't yet tested it.  

I've created a PR so that you can track it / review it.  When I update it from any testing, I'll post a comment so you know.   You should have the ability to push changes into the repo too if you believe somethings not quite right.

**Comment by hamano** [comment]
Why does your patch require both header and footer?
Someone would want use only one header or footer.
I'll review and change your patch then merge.

**Comment by netniV** [comment]
It's not finished yet.  There are various aspects that were not quite right.  So, I'm improving them.  I was doing that at the moment to ensure that it had in fact picked up the configuration correctly.  I've made quite a few changes today with QA testing.

**Comment by hamano** [comment]
I just remembered the reason to aborted the  implementation of the feature in the past.
It's difficult to include files safely.
I will implement this myself.
Thank you.

**Comment by netniV** [comment]
I don't believe that it is.  Most of the work is done.

**Comment by netniV** [comment]
I've just pushed another round of updates through.  I haven't managed to get the check_config call to work properly under 2.4 as I was expect it to loop through both those and the create/merge config routines when apache starts up but my understanding might not quite be there.

**Comment by netniV** [comment]
Also, at the moment, the doc_contents() routine is including a comment whilst I debug, but long term they should not output since it could potentially invalidate in document formats other than HTML

**Comment by hamano** [comment]
Sorry, I dont want implement Markdown(Header/Footer)File.
Your code is unsafe, because access control is inadequate.
If you want do it, you should call the sub request with ap_sub_req_lookup_uri().
I just implemented Markdown(Header|Footer)Html.
https://github.com/hamano/apache-mod-markdown/commit/c8fb35a4a6d6fd2d964efb0b4a6bb15fef2eca70
This will satisfy most requirements.
I do not want to bring security risks into mod_markdown.
Thank you.

**Comment by hamano** [comment]
now you can set
~~~
MarkdownFooterHtml    "<hr><h1>Testing Headers</h1><hr>"
MarkdownFooterHtml    "<hr><h1>Testing Footers</h1><hr>"
~~~

**Comment by hamano** [comment]
FollowSymLinks, IP address restriction in Location(Match)? directive
There are many things to check.
r->filename is already passed access control check.

**Comment by netniV** [comment]
Whilst that may be true for r->filename, these are server configuration options that are set by the server admin, not ones requested by a client.  No different to setting the directory of an Alias or a Virtual Server.

**Comment by netniV** [comment]
One way to lock it down further (again I think that should be configurable) would be limit files to being in the (virtual)server directories by using `ap_server_root_relative()` to verify the filename has the sites path as a prefix.

**Comment by netniV** [comment]
I now have this fully working (without the above optional restriction).  It gives greater flexibility and allows for configuration inheritance.   This allows you to tweak the header, or footer being included dependant on where you are (or even output/css type).  I'm going to rebase it what you've changed so that both features are available by changing ->header to ->headerhtml and ->footer to ->footerhtml then introducing ->footerfile and ->headerfile for clarity.  

Could use the same field but to avoid confusion, safer that way.

**Comment by terroo** [comment]
How to use MarkdownFlags ? I am trying to change the 'title' and I don't know how.
