### ISSUE TITLE
Add mod-markdown to release name

### ISSUE THREAD

**Issue by dago** [hamano/apache-mod-markdown#5]
It would be nice if you could add `apache-mod-markdown-1.0.1.tar.gz` to the release name. At the moment is it just `1.0.1.tar.gz` and a common name would be easier for downstream packagers like me.

**Comment by hamano** [comment]
It seems depends tag name.
I'm feeling redundancy that including project name in tag name.
I want to follow consuetude of common gh project.
Many project seem to use just 1.0.1 for tag name.

**Comment by dago** [comment]
It seems possible to provide the downloadable tarball in a different format, for an example see https://github.com/rockdaboot/libpsl/releases Our build system uses the tarball name for archiving and when multiple projects use just the version collisions occur which must be resolved manually. The libpsl-0.7.1.tar.gz is bootstrapped with autotools here as opposed to "Source Code (tar.gz)" which is just a snapshot of the repo.

**Comment by hamano** [comment]
OK, I just released apache-mod-markdown-1.0.2.tar.bz2 like libpsl project.
I might forget release file, so that I have not the habit.
Thank you.
