### ISSUE TITLE
Issue building on Debian Jessie

### ISSUE THREAD

**Issue by c4s4** [hamano/apache-mod-markdown#8]
Hello,

I had a problem building on Debian Jessie :

--8<-----------------------------------------------------------------------------
$ make
make  all-am
make[1]: Entering directory '/home/casa/tmp/apache-mod-markdown-1.0.2'
/bin/bash ./libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -D_LARGEFILE64_SOURCE   -Wall `/usr/bin/apxs2 -q CFLAGS` -I`/usr/bin/apxs2 -q INCLUDEDIR` -I/usr/include -g -O2 -MT libmodmarkdown_la-mod_markdown.lo -MD -MP -MF .deps/libmodmarkdown_la-mod_markdown.Tpo -c -o libmodmarkdown_la-mod_markdown.lo `test -f 'mod_markdown.c' || echo './'`mod_markdown.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -D_LARGEFILE64_SOURCE -Wall -pipe -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -I/usr/include/apache2 -I/usr/include -g -O2 -MT libmodmarkdown_la-mod_markdown.lo -MD -MP -MF .deps/libmodmarkdown_la-mod_markdown.Tpo -c mod_markdown.c  -fPIC -DPIC -o .libs/libmodmarkdown_la-mod_markdown.o
In file included from /usr/include/apache2/ap_config.h:25:0,
                 from /usr/include/apache2/httpd.h:44,
                 from mod_markdown.c:40:
/usr/include/apache2/ap_hooks.h:39:17: fatal error: apr.h: No such file or directory
 #include "apr.h"
                 ^
compilation terminated.
Makefile:463: recipe for target 'libmodmarkdown_la-mod_markdown.lo' failed
make[1]: *** [libmodmarkdown_la-mod_markdown.lo] Error 1
make[1]: Leaving directory '/home/casa/tmp/apache-mod-markdown-1.0.2'
Makefile:341: recipe for target 'all' failed
make: *** [all] Error 2
--8<-----------------------------------------------------------------------------

I fixed the issue editing Makefile and replacing :

--8<-----------------------------------------------------------------------------
apache_CFLAGS = `/usr/bin/apxs2 -q CFLAGS` -I`/usr/bin/apxs2 -q INCLUDEDIR`
--8<-----------------------------------------------------------------------------

with:

--8<-----------------------------------------------------------------------------
apache_CFLAGS = `/usr/bin/apxs2 -q CFLAGS` -I`/usr/bin/apxs2 -q INCLUDEDIR` -I/usr/include/apr-1.0
--8<-----------------------------------------------------------------------------

This fixed the problem, but I am sure this is not the right way ;o)

**Comment by hamano** [comment]
hmm it seems apxs behavior was changed since debian jessie.
debian wheezy:
~~~
% /usr/bin/apxs2 -q CFLAGS
-D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -D_LARGEFILE64_SOURCE -D_REENTRANT -I/usr/include -I/usr/include/apr-1.0 -I/usr/include/openssl -I/usr/include/xmltok -pthread
~~~
debian jessie :
~~~
% /usr/bin/apxs2 -q CFLAGS 
-pipe -g -O2 -fstack-protector-strong -Wformat -Werror=format-security
~~~

I  just fixed it.
Thank you for your reporting!

**Comment by c4s4** [comment]
You're welcome. I have tried to build on Debian Jessie from master and it
works fine. Thanks!

2015-10-09 9:09 GMT+02:00 HAMANO Tsukasa <notifications@github.com>:

> hmm it seems apxs behavior was changed since debian jessie.
> debian wheezy:
>
> % /usr/bin/apxs2 -q CFLAGS
> -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -D_LARGEFILE64_SOURCE -D_REENTRANT -I/usr/include -I/usr/include/apr-1.0 -I/usr/include/openssl -I/usr/include/xmltok -pthread
>
> debian jessie :
>
> % /usr/bin/apxs2 -q CFLAGS
> -pipe -g -O2 -fstack-protector-strong -Wformat -Werror=format-security
>
> I just fixed it.
> Thank you for your reporting!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hamano/apache-mod-markdown/issues/8#issuecomment-146774531>
> .
>



-- 
Michel Casabianca

**Comment by sigboe** [comment]
`./configure --with-apxs=/usr/bin/apxs2 --with-discount=/usr` and then `make` Then I follow up with `sudo make install` which outputs:

    install -D .libs/libmodmarkdown.so `/usr/bin/apxs2 -q LIBEXECDIR`/mod_markdown.so

and add the line `LoadModule markdown_module modules/mod_markdown.so` to my sites available. But when I try to restart apache I get

```
● apache2.service - LSB: Apache2 web server
   Loaded: loaded (/etc/init.d/apache2)
   Active: failed (Result: exit-code) since Sat 2015-10-17 12:08:02 CEST; 1min 52s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 13311 ExecStop=/etc/init.d/apache2 stop (code=exited, status=0/SUCCESS)
  Process: 27140 ExecReload=/etc/init.d/apache2 reload (code=exited, status=0/SUCCESS)
  Process: 13406 ExecStart=/etc/init.d/apache2 start (code=exited, status=1/FAILURE)

Oct 17 12:08:02 Sigurd-TV apache2[13406]: *
Oct 17 12:08:02 Sigurd-TV apache2[13406]: * The apache2 configtest failed.
Oct 17 12:08:02 Sigurd-TV apache2[13406]: Output of config test was:
Oct 17 12:08:02 Sigurd-TV apache2[13406]: apache2: Syntax error on line 220 of /etc/apache2/apache2.conf: Syntax error on line 17 of /etc/apache2/sites-enabled/000-default.conf: Cannot load modules/mod_markdown.so into...file or directory
Oct 17 12:08:02 Sigurd-TV apache2[13406]: Action 'configtest' failed.
Oct 17 12:08:02 Sigurd-TV apache2[13406]: The Apache error log may have more information.
Oct 17 12:08:02 Sigurd-TV systemd[1]: apache2.service: control process exited, code=exited status=1
Oct 17 12:08:02 Sigurd-TV systemd[1]: Failed to start LSB: Apache2 web server.
Oct 17 12:08:02 Sigurd-TV systemd[1]: Unit apache2.service entered failed state.
Oct 17 12:08:02 Sigurd-TV systemd[1]: apache2.service failed.
```

So I add the full path of the module in sites available, and it worked :smile: Thank you very much
